version: "3.9"

services:
  ecommerce-admin:
    build:
      context: ./ecommerce-admin
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ecommerce-admin:latest
    container_name: ecommerce-admin
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - FRONTEND_STORE_URL=${FRONTEND_STORE_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL_ADMIN}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}

  ecommerce-store:
    build:
      context: ./ecommerce-store
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ecommerce-store:latest
    container_name: ecommerce-store
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL_STORE}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ecommerce-admin
      - ecommerce-store
